#spring.application.name=booking-service
#
#spring.datasource.url=jdbc:mysql://localhost:3306/uber_db_local
#spring.datasource.username=root
#spring.datasource.password=password
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=validate

#server.port=7004

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/uber_db_local
    username: root
    password: ${UBER_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

server:
  port: 7004


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
